# Production Environment Configuration
server.port=80

# Use PostgreSQL or MySQL in PROD (Dummy configuration)
spring.datasource.url=jdbc:postgresql://prod-db.honeywell.com:5432/sensordb
spring.datasource.username=prod_user
spring.datasource.password=secure_password

# Disable H2 console in PROD
spring.h2.console.enabled=false

# Validate schema only in PROD
spring.jpa.hibernate.ddl-auto=validate

# Restrict actuator endpoints in prod for security
management.endpoints.web.exposure.include=health,info
