# Development Environment Configuration
server.port=8080

# H2 Database configuration for DEV
spring.datasource.url=jdbc:h2:mem:sensordb_dev;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console for DEV
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate auto table creation
spring.jpa.hibernate.ddl-auto=create

# Expose all actuator endpoints in dev
management.endpoints.web.exposure.include=*
